---
title: "PhyloAcc action items - 2022.10.07"
author: "[gwct](https://gwct.github.io/)"
date: "`r format(Sys.time(), '%m/%d/%Y %H:%M:%S %Z')`"
output:
  #html_document:
  rmdformats::robobook:
    highlight: kate
    includes:
      in_header: '../html-chunks/rmd_header.html'
    df_print: paged
    code_folding: hide
    number_sections: true
    toc_depth: 3
---


1. #### Decide on labels for simulations. (Everyone)
2. #### Re-generate figures with correct labels after (1) is resolved. For example, changing "inputCaseX" in Figure 2 to "Convergent" or whatever we decide. (Han, Gregg)
3. #### Check accuracy of simulation figure (Fig. 2). (Gregg/everyone)
4. #### Figure 3: clarify axes and scenarios, maybe add an example PR curve? (Han, maybe Gregg)
5. #### Discuss again whether boxplots easily show the accuracy of the Z matrix. (Everyone)
6. #### Change labels on boxplots to match generic labels on simulation figure (e.g. "K" instead of "Kiwi"). (Han, Gregg)
7. #### Re-visit Figure 9. (Everyone)
8. #### Add a figure for the marine mammal results (Han, Zhirui, Gregg)
9. #### More clean up of the draft. (Han, Zhirui, Gregg, Tim)
10. #### Clean up intro (statistics and citations). (Gregg)
11. #### Discussion (Everyone)

Later... Appendix/supplement...
