---
title: "Turtle assembly stats"
author: "[gwct](https://gwct.github.io/)"
date: "`r format(Sys.time(), '%m/%d/%Y %H:%M:%S %Z')`"
output:
  #html_document:
  rmdformats::robobook:
    highlight: kate
    includes:
      in_header: '../html-chunks/rmd_header.html'
    df_print: paged
    code_folding: hide
    number_sections: true
    toc_depth: 3
---

```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(ggplot2)
#library(cowplot)
#library(ggbeeswarm)
#library(ggpubr)
#library(plyr)
library(dplyr)
#library(kableExtra)
source("../lib/design.r")
```

[< Back to samples](index.html)

Assemblies from each genome were downloaded from NCBI on 07.22.2021

```{r read-data}
in_data = read.csv("../../data/turtles.csv", header=T, comment.char="#")
in_data = subset(in_data, Alternate=="N")
```

## Reported coverage

```{r coverage-fig, out.width="66%", fig.align="center"}
in_data$Label = factor(in_data$Label, levels=in_data$Label[order(in_data$Coverage, decreasing=T)])
cov_p = ggplot(in_data, aes(x=Label, y=Coverage, color=Annotation.file)) +
  geom_segment(aes(x=Label, y=0, xend=Label, yend=Coverage), linetype="dotted", color="#666666") +
  geom_point(size=4) +
  scale_y_continuous(expand=c(0,0), limits=c(0,225)) +
  ylab("Reported X coverage") +
  xlab(paste("")) +
  scale_color_manual(name="Annotated", values=c("Y"=corecol(pal="wilke", numcol=1, offset=1), "N"=corecol(pal="wilke", numcol=1))) +
  bartheme() +
  theme(axis.text.x=element_text(angle=45, hjust=1, size=10),
        legend.title=element_text(size=12),
        legend.position="bottom")
print(cov_p)

cat("Max coverage: ", max(in_data$Coverage), "X\n",
    "Average coverage: ", signif(mean(in_data$Coverage), 4), "X\n",
    "Min coverage: ", min(in_data$Coverage), "X\n", sep="")
```

## Number of scaffolds

```{r scaffold-fig, out.width="66%", fig.align="center"}
in_data$Label = factor(in_data$Label, levels=in_data$Label[order(in_data$Scaffolds, decreasing=T)])
scaff_p = ggplot(in_data, aes(x=Label, y=Scaffolds, fill=Annotation.file)) +
  # geom_segment(aes(x=Label, y=0, xend=Label, yend=Scaffolds), linetype="dotted", color="#666666") +
  geom_bar(stat="identity") +
  scale_y_continuous(expand=c(0,0)) +
  ylab("# scaffolds") +
  xlab(paste("")) +
  scale_fill_manual(name="Annotated", values=c("Y"=corecol(pal="wilke", numcol=1, offset=1), "N"=corecol(pal="wilke", numcol=1))) +
  bartheme() +
  theme(axis.text.x=element_text(angle=45, hjust=1, size=10),
        legend.title=element_text(size=12),
        legend.position="bottom")
print(scaff_p)

cat("Max # scaffold: ", max(in_data$Scaffolds), "\n",
    "Average # scaffolds: ", signif(mean(in_data$Scaffolds), 4),  "\n",
    "Min # scaffold: ", min(in_data$Scaffolds), sep="")
```

## Scaffold N50

```{r n50-fig, out.width="66%", fig.align="center"}
in_data$Label = factor(in_data$Label, levels=in_data$Label[order(in_data$Scaffold.N50, decreasing=T)])
n50_p = ggplot(in_data, aes(x=Label, y=Scaffold.N50, color=Annotation.file)) +
  geom_segment(aes(x=Label, y=0, xend=Label, yend=Scaffold.N50), linetype="dotted", color="#666666") +
  geom_point(size=4) +
  scale_y_continuous(expand=c(0,0), limits=c(0,max(in_data$Scaffold.N50) + 7500000)) +
  ylab("Scaffold N50") +
  xlab(paste("")) +
  scale_color_manual(name="Annotated", values=c("Y"=corecol(pal="wilke", numcol=1, offset=1), "N"=corecol(pal="wilke", numcol=1))) +
  bartheme() +
  theme(axis.text.x=element_text(angle=45, hjust=1, size=10),
        legend.title=element_text(size=12),
        legend.position="bottom")
print(n50_p)

cat("Max scaffold N50: ", max(in_data$Scaffold.N50), "\n",
    "Average scaffold N50: ", signif(mean(in_data$Scaffold.N50), 4), "\n",
    "Min scaffold N50: ", min(in_data$Scaffold.N50), sep="")
```

## Scaffold N50 by # Scaffolds

```{r scaffold-n50-fig, out.width="66%", fig.align="center"}
scaff_n50_p = ggplot(in_data, aes(x=Scaffolds, y=Scaffold.N50, color=Annotation.file)) +
  geom_smooth(method="lm", se=F, linetype="dashed", size=1.5, color="#666666") +
  geom_point(size=4, alpha=0.5) +
  #scale_y_continuous(expand=c(0,0), limits=c(0,max(in_data$Scaffold.N50) + 7500000)) +
  ylab("Scaffold N50") +
  xlab("# Scaffolds") +
  scale_color_manual(name="Annotated", values=c("Y"=corecol(pal="wilke", numcol=1, offset=1), "N"=corecol(pal="wilke", numcol=1))) +
  bartheme() +
  theme(axis.text.x=element_text(angle=45, hjust=1, size=10),
        legend.title=element_text(size=12),
        legend.position="bottom")
print(scaff_n50_p)
```

[< Back to samples](index.html)