---
title: "PhyloAcc accelerated mammal elements"
author: "[gwct](https://gwct.github.io/)"
date: "`r format(Sys.time(), '%m/%d/%Y %H:%M:%S %Z')`"
output:
  #html_document:
  rmdformats::robobook:
    highlight: kate
    includes:
      in_header: '../html-chunks/rmd_header.html'
    df_print: paged
    code_folding: hide
    number_sections: true
    toc_depth: 3
---


```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(ggplot2)
library(dplyr)
library(cowplot)
library(phangorn)
library(ape)
library(kableExtra)
library(here)
source("../lib/design.r")
```

[< Back ](index.html)

Comparisons of gene trees for elements in the mammal dataset inferred to be accelerated using the species tree model

```{r read, out.width="100%", fig.align = "center", warning=FALSE}
species_tree_file = here("docs", "data", "mammal.tre")
species_tree = read.tree(file=species_tree_file)

gene_tree_file = here("docs", "data", "mammal-acc-gene-trees-labeled.txt")
gene_trees = read.csv(gene_tree_file, sep="\t", header=F)
names(gene_trees) = c("locus.id", "tree.str")

gene_tree_results_file = here("docs", "data", "mammal_gt_model_elem_lik.txt")
elem_lik = read.csv(gene_tree_results_file, sep="\t", header=T)
names(elem_lik)[1] = "run.id"

id_key_file = here("docs", "data", "mammal-id-key.txt")
id_key = read.csv(id_key_file, sep="\t", header=F)
names(id_key) = c("run.id", "locus.id")

data = merge(gene_trees, id_key, by="locus.id")
data = merge(data, elem_lik, by="run.id")

```

# Summary

```{r acc-summary, out.width="50%", fig.align = "center", warning=FALSE}

data$acc = FALSE
data$acc[data$logBF1 > 10 & data$logBF2 > 1] = TRUE

total_elem = nrow(data)
acc_elem = nrow(subset(data, acc==TRUE))
prop_acc_elem = acc_elem / total_elem

table_data = data.frame("Category"=c("Total elements", "Accelerated elements", "Proportion accelerated"), "Value"=c(total_elem, acc_elem, signif(prop_acc_elem, 4)))
table_data$Value <- sub("0+$", "", as.character(table_data$Value))

table_data %>% kable() %>% kable_styling(bootstrap_options=c("striped", "condended", "responsive"), full_width=F)

```

# Bayes factor and Robinson-Foulds distance to species tree

```{r calc-rf, out.width="80%", fig.align = "center", warning=FALSE, fig.height=2.5}
data$rf = NA
data$num.tips = NA

for(i in 1:nrow(data)){
  gt = read.tree(text=data[i,]$tree.str)
  # Read the gene tree as a phylo object
  
  cur_tips = gt$tip.label
  pruned_tree = drop.tip(species_tree, species_tree$tip.label[-match(cur_tips, species_tree$tip.label)])
  # Get a list of the tips and prune the species tree to contain only those tips
  
  cur_rf = RF.dist(pruned_tree, gt, normalize=F)
  # Calculate RF between the pruned species tree and the gene tree
  
  data[i,]$rf = cur_rf
  data[i,]$num.tips = length(cur_tips)
  # Add the gene tree info to the df, with a special case for when the RF is 0
}
# Read all the gene trees

```

## BF1

```{r bf1-rf, out.width="60%", fig.align = "center", warning=FALSE, fig.height=6}

p = ggplot(subset(data, logBF1 < 200), aes(x=logBF1, y=rf, color=acc)) +
  geom_point(size=2, alpha=0.3) +
  #geom_quasirandom(size=2, width=0.25, alpha=0.25, color="#666666") +
  #geom_boxplot(outlier.shape=NA, alpha=0.75, width=0.5, color="#666666") +
  scale_color_manual(values=corecol(numcol=2, pal="wilke")) +
  labs(color="Accelerated?") +
  #scale_y_continuous(expand=c(0,0)) +
  xlab("log BF1") +
  ylab("RF to species tree") +
  bartheme() +
  theme(legend.position="bottom",
        legend.title=element_text())
print(p)

```

## BF2

```{r bf2-rf, out.width="60%", fig.align = "center", warning=FALSE, fig.height=6}

p = ggplot(subset(data, logBF2 > -200), aes(x=logBF2, y=rf, color=acc)) +
  geom_point(size=2, alpha=0.3) +
  #geom_quasirandom(size=2, width=0.25, alpha=0.25, color="#666666") +
  #geom_boxplot(outlier.shape=NA, alpha=0.75, width=0.5, color="#666666") +
  scale_color_manual(values=corecol(numcol=2, pal="wilke")) +
  labs(color="Accelerated?") +
  #scale_y_continuous(expand=c(0,0)) +
  xlab("log BF2") +
  ylab("RF to species tree") +
  bartheme() +
  theme(legend.position="bottom",
        legend.title=element_text())
print(p)

```

## BF1 / BF2

```{r bf-ratio-rf, out.width="60%", fig.align = "center", warning=FALSE, fig.height=6}

data$bf.ratio = data$logBF1 / data$logBF2

p = ggplot(subset(data, bf.ratio < 10 & bf.ratio > -10), aes(x=bf.ratio, y=rf, color=acc)) +
  geom_point(size=2, alpha=0.3) +
  #geom_quasirandom(size=2, width=0.25, alpha=0.25, color="#666666") +
  #geom_boxplot(outlier.shape=NA, alpha=0.75, width=0.5, color="#666666") +
  scale_color_manual(values=corecol(numcol=2, pal="wilke")) +
  labs(color="Accelerated?") +
  #scale_y_continuous(expand=c(0,0)) +
  xlab("log BF1 / log BF2") +
  ylab("RF to species tree") +
  bartheme() +
  theme(legend.position="bottom",
        legend.title=element_text())
print(p)

```



[< Back ](index.html)

















